# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFzN3CHszWcoFKSNvFL-3-gYAOiU29nj
"""

import pandas as pd
baza={
    "FISH":[ "Abdubaliyev Doniyorbek","Abduhamidov Namozboy","Abdullajonov Muhammadqodir","Abdumalikov Anvarjon","Ahmadjonov Diyorbek","Alekseyeva Xadicha","Halimov Ozodbek","Ibrohimova Adolatxon","Ikromov Islomjon","Xolmatova Nilufarxon" ],

    "Yoshi":["11","10","9","8","7","6","15","17","18","20"   ],
    "Jinsi":["o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","qiz bola","o'g'il bola","qiz bola","o'g'il bola","qiz bola"],
"qaysi universitetda o'qishi":["TATU","FARDU","TATU","TATU","TATU","FARDU","FARDU","FARDU","TATU","TATU"],
    "Manzili":["Farg'ona shahar","Farg'ona shahar","Farg'ona shahar","Farg'ona shahar","Namangan shahar","Namangan shahar","Namangan shahar","Farg'ona shahar","Farg'ona shahar","Farg'ona shahar",]

}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="qiz bola"]
print(filtr)

"""# Новый раздел"""